### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by bhavandar** [bhavandar/Plant-Diseases-Recognition#1]
I created a new virtual environment and installed all the required dependencies. 
When I tried to run `py manage.py runserver` command and got the following error:

> Using TensorFlow backend.
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\tensorflow\python\framework\dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001FDBF77B2F0>
Traceback (most recent call last):
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\management\commands\runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\management\base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\management\base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\checks\registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\urls\resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\utils\functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\urls\resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files (x86)\Python35-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\nmule\OneDrive\Desktop\Plant-Diseases-Recognition\plant_diseases\plant_diseases\urls.py", line 8, in <module>
    path('', include('plant_app.urls')),
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "C:\Program Files (x86)\Python35-64\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\nmule\OneDrive\Desktop\Plant-Diseases-Recognition\plant_diseases\plant_app\urls.py", line 2, in <module>
    from . import views
  File "C:\Users\nmule\OneDrive\Desktop\Plant-Diseases-Recognition\plant_diseases\plant_app\views.py", line 2, in <module>
    from keras.preprocessing import image
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\utils\__init__.py", line 27, in <module>
    from .multi_gpu_utils import multi_gpu_model
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\utils\multi_gpu_utils.py", line 7, in <module>
    from ..layers.merge import concatenate
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\layers\__init__.py", line 4, in <module>
    from ..engine.base_layer import Layer
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\engine\__init__.py", line 8, in <module>
    from .training import Model
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\engine\training.py", line 21, in <module>
    from . import training_arrays
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\keras\engine\training_arrays.py", line 8, in <module>
    from scipy.sparse import issparse
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\__init__.py", line 156, in <module>
    from . import fft
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\fft\__init__.py", line 76, in <module>
    from ._basic import (
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\fft\_basic.py", line 1, in <module>
    from scipy._lib.uarray import generate_multimethod, Dispatchable
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\_lib\uarray.py", line 27, in <module>
    from ._uarray import *
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\_lib\_uarray\__init__.py", line 114, in <module>
    from ._backend import *
  File "C:\Users\nmule\OneDrive\Desktop\saroj_leaf_env\lib\site-packages\scipy\_lib\_uarray\_backend.py", line 1, in <module>
    from typing import (
ImportError: cannot import name 'Type'

I had faced the same issue when I had installed dependencies in the global python earlier.
Note: I only have Python 3.5 installed. The global python has no additional packages installed. Everything is in the virtual env. The global env is untouched.

**Comment by bhavandar** [comment]
I have the following packages installed:

> absl-py==0.9.0
astor==0.8.1
certifi==2019.11.28
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
Django==2.1.7
django-cors-headers==2.4.0
djangorestframework==3.9.1
gast==0.3.3
grpcio==1.27.2
h5py==2.10.0
idna==2.9
itypes==1.1.0
Jinja2==2.11.1
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
Markdown==3.2.1
MarkupSafe==1.1.1
numpy==1.18.2
Pillow==5.4.0
pipenv==2018.11.26
protobuf==3.11.3
pytz==2019.3
PyYAML==5.3.1
requests==2.23.0
scipy==1.4.1
six==1.14.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
uritemplate==3.0.1
urllib3==1.25.8
virtualenv-clone==0.5.3
Werkzeug==1.0.0

**Comment by bhavandar** [comment]
**Solved**
The typing feature is developed for python 3.6 and above. 
The error can simply be solved by using a newer python version.
